---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1575278/public_html/
    - /bin/cp -R public $DEPLOYPATH
    # - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R font $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH